apiVersion: v1
kind: Service
metadata:
  name: jibaek-gh-action-demo-app-service
spec:
  type: NodePort
  selector:
    app: jibaek-gh-action-demo-app
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 80