apiVersion: v1
kind: Service
metadata:
  name: jibaek-resume-app-service
spec:
  type: NodePort
  selector:
    app: jibaek-resume-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80