apiVersion: apps/v1
kind: Deployment
metadata:
  name: jibaek-resume-app-deployment
  labels:
    app: jibaek-resume-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jibaek-resume-app
  template:
    metadata:
      labels:
        app: jibaek-resume-app
    spec:
      containers:
      - name: jibaek-resume-app
        image: asia-northeast3-docker.pkg.dev/astute-curve-461807-v0/jibaek-resume/jibaek-resume:prod-20250710-7a597c7339
        ports:
        - containerPort: 80
